language: python
python:
- "2.7"
- "2.6"
env:
- FLASK=0.9
- SECRET_KEY=jklasdfjadjsfahsuyo8u7p0478980789079078324125

install: 
- pip install -r requirements.txt --use-mirrors

before_script:
- psql -c 'create database recordtrac;' -U postgres
- python travis_db_setup.py

script:
- python tests.py