language: python

python:
- "2.7"

env:
- SECRET_KEY=jklasdfjadjsfahsuyo8u7p0478980789079078324125

install: 
- pip install -r requirements.txt

before_script:
- psql -c 'create database recordtrac;' -U postgres
- python travis_db_setup.py

script:
- python tests.py